## Retrieve parsed collection

In [6]:
import pandas as pd
import numpy as np
from gensim import models, similarities
from tqdm import tqdm
import spacy
import joblib
from modules.db import mongo_base
from sklearn.feature_extraction.text import CountVectorizer, HashingVectorizer, TfidfVectorizer, TfidfTransformer
from sklearn.feature_extraction import FeatureHasher, DictVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from modules.utils.CustomTwokenizer import CustomTwokenizer

### Store feature collection as dataframe

In [12]:
# connection_params = ["twitter", "crowdflower_features"]
# client = mongo_base.connect()
# db_name = connection_params[0]
# connection_params.insert(0, client)

# query = {}
# query["filter"] = {}
# query["projection"] = {}
# query["limit"] = 0
# query["skip"] = 0
# query["no_cursor_timeout"] = True
# cursor = mongo_base.finder(connection_params, query, False)
# df = pd.DataFrame(list(cursor))
# df.head()

#### Merge dataframes

In [13]:
# connection_params = ["twitter", "crowdflower_features_emo"]
# client = mongo_base.connect()
# db_name = connection_params[0]
# connection_params.insert(0, client)

# query = {}
# query["filter"] = {}
# query["projection"] = {"emotions":1}
# query["limit"] = 0
# query["skip"] = 0
# query["no_cursor_timeout"] = True
# cursor = mongo_base.finder(connection_params, query, False)
# df_emo = pd.DataFrame(list(cursor))
# df = pd.DataFrame.merge(df, df_emo, on="_id")
# df.head()

#### Pickle the raw feature collection

In [11]:
spacy_en_model = "en_core_web_md"
spacy_glove_model = "en_vectors_glove_md"
crowdflower_persistence_raw = 'data/persistence/df/crowdflower_features_raw.pkl.compressed'
crowdflower_persistence = 'data/persistence/df/crowdflower_features.pkl.compressed'
nlp = spacy.load(spacy_en_model, create_make_doc=CustomTwokenizer)
# joblib.dump(df, crowdflower_persistence_raw, compress=True)

['data/persistence/df/crowdflower_features_raw.pkl.compressed']

In [ ]:
df = joblib.load(crowdflower_persistence_raw)

### Create a dataframe with classifier features

In [15]:
feat_df = df[['_id', 'text', 'annotation_label', 'hs_keyword_matches', 'hs_keyword_count', 'unknown_words', 'unknown_words_count', 'comment_length', 'brown_cluster_ids', 'feat_dependency_contexts', 'feat_word_dep_root', 'feat_pos_dep_rootPos', 'feat_word_root_rootparent', 'feat_dep_unigrams', 'feat_dep_bigrams', 'feat_dep_trigrams']]

_id  \
0  58c659be6541913eb7f119dd   
1  58c659be6541913eb7f119de   
2  58c659be6541913eb7f119df   
3  58c659be6541913eb7f119e0   
4  58c659be6541913eb7f119e1   

                                                text annotation_label  \
0     Warning : penny boards will make you a faggot     not_offensive   
1                                        Fuck dykes        hatespeech   
2  user_mention user_mention user_mention user_me...       hatespeech   
3  " user_mention : " user_mention : user_mention...       hatespeech   
4  user_mention You heard me bitch but any way I'...    not_offensive   

  hs_keyword_matches  hs_keyword_count unknown_words  unknown_words_count  \
0           [faggot]                 1            []                    0   
1                 []                 0            []                    0   
2           [faggot]                 1      [jefree]                    1   
3              [fag]                 1      [neeeee]                    1   
4            [bitch]                 1       [nigga]                    1   

   comment_length                                  brown_cluster_ids  \
0               9           [966, 228, 989, 333, 442, 4618, 602, 19]   
1               2                                                 []   
2              14                   [124, 3690, 966, 2442, 1684, 86]   
3              15             [228, 228, 1214, 19, 28650, 1014, 981]   
4              20  [858, 26282, 1898, 2485, 148, 12266, 1349, 753...   

                            feat_dependency_contexts  \
0  [warning_:_punct, warning_make_acl, penny_boar...   
1      [fuck_dykes_compoundINV, dykes_fuck_compound]   
2  [user_mention_user_mention_compoundINV, user_m...   
3  [user_mention_"_punct, user_mention_:_punct, u...   
4  [user_mention_heard_relcl, user_mention_bitch_...   

                                  feat_word_dep_root  \
0  [warning_ROOT_warning, penny_compound_boards, ...   
1            [fuck_compound_dykes, dykes_ROOT_dykes]   
2  [user_mention_compound_user_mention, user_ment...   
3  [user_mention_ROOT_user_mention, user_mention_...   
4  [user_mention_ROOT_user_mention, you_nsubj_hea...   

                                feat_pos_dep_rootPos  \
0  [NN_ROOT_NN, NN_compound_NNS, NNS_nsubj_VB, MD...   
1                   [NNP_compound_VBZ, VBZ_ROOT_VBZ]   
2  [NN_compound_NN, NN_compound_NN, NN_compound_N...   
3  [NN_ROOT_NN, NN_appos_NN, NN_nsubj_VBZ, VBZ_ac...   
4  [NN_ROOT_NN, PRP_nsubj_VBD, VBD_relcl_NN, PRP_...   

                           feat_word_root_rootparent  \
0  [warning_warning_warning, penny_boards_make, b...   
1              [fuck_dykes_dykes, dykes_dykes_dykes]   
2  [user_mention_user_mention_user_mention, user_...   
3  [user_mention_user_mention_user_mention, user_...   
4  [user_mention_user_mention_user_mention, you_h...   

                                   feat_dep_unigrams  \
0  [warning_warning_ROOT_NN, penny_boards_compoun...   
1    [fuck_dykes_compound_NNP, dykes_dykes_ROOT_VBZ]   
2  [user_mention_user_mention_compound_NN, user_m...   
3  [user_mention_user_mention_ROOT_NN, user_menti...   
4  [user_mention_user_mention_ROOT_NN, you_heard_...   

                                    feat_dep_bigrams  \
0  [warning_warning_ROOT_NN | penny_boards_compou...   
1   [fuck_dykes_compound_NNP | dykes_dykes_ROOT_VBZ]   
2  [user_mention_user_mention_compound_NN | user_...   
3  [user_mention_user_mention_ROOT_NN | user_ment...   
4  [user_mention_user_mention_ROOT_NN | you_heard...   

                                   feat_dep_trigrams  
0  [warning_warning_ROOT_NN | penny_boards_compou...  
1                                                 []  
2  [user_mention_user_mention_compound_NN | user_...  
3  [user_mention_user_mention_ROOT_NN | user_ment...  
4  [user_mention_user_mention_ROOT_NN | you_heard...

In [16]:
# joblib.dump(feat_df, crowdflower_persistence, compress=True)
feat_df = joblib.load(crowdflower_persistence)
feat_df.head()

['data/persistence/df/crowdflower_features.pkl.compressed']

In [5]:
df[0:1]['dep_bigrams'][0][0]
hasher = FeatureHasher(input_type='string', non_negative=True)
v = DictVectorizer(sparse=False)
# raw_X = hasher.transform(df[0:1]['brown_cluster_ids'])
df[0:1]['bigrams'][0][0]
D = [{'bigram': 'Warning penny'}, {'bigram': 'penny boards'}, {'bigram': 'boards will'}, {'bigram': 'boards will'}]
trans = v.fit_transform(D)
v.inverse_transform(trans)
v.get_feature_names()
# raw_X.toarray()
# print(df[0:1]['bigrams'][0])
df[0:1]

_id annotation_label  avg_token_length  \
0  58c659be6541913eb7f119dd    not_offensive               4.0   

                                             bigrams  \
0  [Warning penny, penny boards, boards will, wil...   

                          brown_cluster_ids  \
0  [966, 228, 989, 333, 442, 4618, 602, 19]   

                                     char_pentagrams  \
0  [penny, warni, arnin, aggot, board, rning, fag...   

                                      char_quadgrams  \
0  [aggo, warn, arni, penn, oard, ards, enny, nin...   

                                       char_trigrams  comment_length  \
0  [pen, war, nin, mak, enn, you, agg, ggo, fag, ...               9   

                                         conllFormat  \
0  [1 warning warning NOUN NN _ 0 ROOT 0:ROOT _, ...   

                         ...                          \
0                        ...                           

                                         noun_chunks  \
0  [{'text': 'warning', 'root': 'warning'}, {'tex...   

                                     pos_dep_rootPos  \
0  [{'pos': 'NN', 'dep': 'ROOT', 'rootPos': 'NN'}...   

                                             text  \
0  Warning : penny boards will make you a faggot    

                             tokens  \
0  [warning, penny, boards, faggot]   

                                            trigrams unknown_words  \
0  [Warning penny boards, penny boards will, boar...            []   

  unknown_words_count  uppercase_token_count  \
0                   0                      0   

                                       word_dep_root  \
0  [{'word': 'warning', 'dep': 'ROOT', 'root': 'w...   

                                   word_root_preRoot  
0  [{'word': 'warning', 'preRoot': 'warning', 'ro...  

[1 rows x 29 columns]

### Setup data split

In [6]:
# let's pick the same random 10% of the data to train with
train_test_set = df.sample(n=int(len(df) / 2), random_state=1965)

X = train_test_set['text']
y = train_test_set['annotation_label']

In [7]:
print("Predicting the labels of the test set...")
print("%d documents" % len(X))
print("%d categories" % len(y.value_counts()))

Predicting the labels of the test set...
7254 documents
2 categories


### Setup generic model experiment

In [9]:
def run_experiment(X, y, pipeline, process_name, num_expts=1):
    scores = list()
    for i in tqdm(range(num_expts)):
        X_train, X_test, y_train, y_test = train_test_split(X, y)
        model = pipeline.fit(X_train, y_train)  # train the classifier
        y_prediction = model.predict(X_test)          # apply the model to the test data
        report = classification_report(y_test, y_prediction)
        score = accuracy_score(y_prediction, y_test)  # compare the results to the gold standard
        scores.append(score)
        print("Classification Report: " + process_name)
        print(report)
        cm = confusion_matrix(y_test, y_prediction)
        print("Confusion matrix:")
        print(cm)
    print(sum(scores) / num_expts)

### Setup naive baseline classification (countVectorizer)

In [12]:
from sklearn.feature_selection import SelectKBest, chi2
# our two ingredients: the ngram counter and the classifier
nm = 5000
vect = CountVectorizer(ngram_range=(3,5), analyzer='char')
clf = LinearSVC()
ch2 = SelectKBest(chi2, k=nm)

# There are just two steps to our process: extracting the ngrams and
# putting them through the classifier. So our Pipeline looks like this:

count_pipeline = Pipeline([
    ('vect', vect),  # extract ngrams from tweet text
    ('kBest', ch2),
    ('clf' , clf),   # feed the output through a classifier
])

# Run the classifcation
run_experiment(X, y, count_pipeline, "CountVectorizer")

100%|██████████| 1/1 [00:03<00:00,  3.23s/it]

Classification Report: CountVectorizer
               precision    recall  f1-score   support

   hatespeech       0.43      0.38      0.40       289
not_offensive       0.88      0.91      0.90      1525

  avg / total       0.81      0.82      0.82      1814

Confusion matrix:
[[ 109  180]
 [ 142 1383]]
0.822491730981


### Setup naive baseline classification (hashingVectorizer)

In [10]:
vect = HashingVectorizer(ngram_range=(3,5), analyzer='char')
clf = LinearSVC()

hashing_pipeline = Pipeline([
    ('vect', vect),  # extract ngrams from tweet text
    ('clf' , clf),   # feed the output through a classifier
])
run_experiment(X, y, hashing_pipeline, "HashingVectorizer")

Classification Report: HashingVectorizer
               precision    recall  f1-score   support

   hatespeech       0.58      0.36      0.44       322
not_offensive       0.87      0.95      0.91      1492

  avg / total       0.82      0.84      0.82      1814

Confusion matrix:
[[ 115  207]
 [  82 1410]]
0.840683572216


### Setup tf-idf baseline classification

In [11]:
vect = TfidfVectorizer(ngram_range=(3,5), analyzer='char')
clf = LinearSVC()

tfidf_pipeline = Pipeline([
    ('vect', vect),  # extract ngrams from tweet text
    ('clf' , clf),   # feed the output through a classifier
])
run_experiment(X, y, tfidf_pipeline, "TfidfVectorizer")

Classification Report: TfidfVectorizer
               precision    recall  f1-score   support

   hatespeech       0.53      0.35      0.42       292
not_offensive       0.88      0.94      0.91      1522

  avg / total       0.83      0.85      0.83      1814

Confusion matrix:
[[ 101  191]
 [  89 1433]]
0.845644983462


### Investigate this

In [14]:
# As much as I want to ignore this, I shouldn't. The fact that the precision score is
# close to the other experiments is troubling

X = train_test_set[['hs_keyword_count', 'comment_length', 'unknown_words_count']]
y = train_test_set['annotation_label']
clf = LinearSVC()

X_train, X_test, y_train, y_test = train_test_split(X, y)
model = clf.fit(X_train, y_train)  # train the classifier
y_prediction = model.predict(X_test)          # apply the model to the test data
report = classification_report(y_test, y_prediction)
print("Classification Report : Random Experiment")
print(report)
cm = confusion_matrix(y_test, y_prediction)
print("Confusion matrix:")
print(cm)
df[0:1]

Classification Report : Random Experiment
               precision    recall  f1-score   support

   hatespeech       0.64      0.07      0.13       295
not_offensive       0.85      0.99      0.91      1519

  avg / total       0.81      0.84      0.79      1814

Confusion matrix:
[[  21  274]
 [  12 1507]]


_id annotation_label  avg_token_length  \
0  58c659be6541913eb7f119dd    not_offensive               4.0   

                                             bigrams  \
0  [Warning penny, penny boards, boards will, wil...   

                          brown_cluster_ids  \
0  [966, 228, 989, 333, 442, 4618, 602, 19]   

                                     char_pentagrams  \
0  [penny, warni, arnin, aggot, board, rning, fag...   

                                      char_quadgrams  \
0  [aggo, warn, arni, penn, oard, ards, enny, nin...   

                                       char_trigrams  comment_length  \
0  [pen, war, nin, mak, enn, you, agg, ggo, fag, ...               9   

                                         conllFormat  \
0  [1\twarning\twarning\tNOUN\tNN\t_\t0\tROOT\t0:...   

                         ...                          \
0                        ...                           

                                         noun_chunks  \
0  [{'root': 'warning', 'text': 'warning'}, {'roo...   

                                     pos_dep_rootPos  \
0  [{'dep': 'ROOT', 'rootPos': 'NN', 'pos': 'NN'}...   

                                             text  \
0  Warning : penny boards will make you a faggot    

                             tokens  \
0  [warning, penny, boards, faggot]   

                                            trigrams unknown_words  \
0  [Warning penny boards, penny boards will, boar...            []   

  unknown_words_count uppercase_token_count  \
0                   0                     0   

                                       word_dep_root  \
0  [{'dep': 'ROOT', 'root': 'warning', 'word': 'w...   

                                   word_root_preRoot  
0  [{'root': 'warning', 'preRoot': 'warning', 'wo...  

[1 rows x 30 columns]

### Dependency tuple experiment

In [13]:
from itertools import chain
X = train_test_set['word_root_preRoot']
y = train_test_set['annotation_label']
clf = LinearSVC()

# http://www.markhneedham.com/blog/2015/03/02/python-scikit-learn-training-a-classifier-with-non-numeric-features/
empty_analyzer = lambda x: x
vect = DictVectorizer()
transformer = TfidfTransformer(smooth_idf=False)
# vect = TfidfVectorizer(analyzer=empty_analyzer)
# hasher = FeatureHasher(input_type='string', non_negative=True)
# X = [[str(res) for res in tmp] for tmp in X]# 
# X = hasher.transform(X)

X = X.tolist()
X = vect.fit_transform([item[0] for item in X]).toarray()
# X = transformer.fit_transform(X)
# vect.vocabulary_
X_train, X_test, y_train, y_test = train_test_split(X, y)
model = clf.fit(X_train, y_train)  # train the classifier
y_prediction = model.predict(X_test)          # apply the model to the test data
report = classification_report(y_test, y_prediction)
print("Classification Report : Random Experiment")
print(report)
cm = confusion_matrix(y_test, y_prediction)
print("Confusion matrix:")
print(cm)

Classification Report : Random Experiment
               precision    recall  f1-score   support

   hatespeech       0.38      0.14      0.20       303
not_offensive       0.85      0.95      0.90      1511

  avg / total       0.77      0.82      0.78      1814

Confusion matrix:
[[  41  262]
 [  68 1443]]


### Extract dependency contexts

In [5]:
test_string = "Austrailian scientists discovers star with telescope"
doc = nlp(test_string)

# elements = []
# dict1 = {"austrailian": "scientists amod"}
# dict2 = {"scientists": "austrailian amod"}
# dict3 = {"scientists": "discovers nsubj"}

# elements.append(dict1)
# elements.append(dict2)
# elements.append(dict3)

# vect = DictVectorizer()
# X = vect.fit_transform(elements)
# X
# vect.inverse_transform(X)

def extract_dep_context(doc):
    dependency_contexts = []
    dependency_contexts_concat = []
    for word in doc:
        if (not str(word.head.prefix_).isalpha() or not str(word.prefix_).isalpha() or "." in word.text or "." in str(word.head)):
            pass
        elif len(list(word.children)) == 0:
            dependency_contexts.append({word.lower_: str(word.head.lower_) + " " + str(word.dep_) + "INV"})
            dependency_contexts_concat.append(word.lower_+ "_" + word.head.lower_ + "_" + str(word.dep_) + "INV")
        elif len(list(word.children)) >= 1:
            for child in word.children:
                if child.lower_ != word.lower_:
                    dependency_contexts.append({word.lower_: str(child.lower_) + " " + str(child.dep_)})
                    dependency_contexts_concat.append(word.lower_ + "_" + child.lower_ + "_" + str(child.dep_))
            if word.dep_ != "ROOT":
                dependency_contexts.append({word.lower_: word.head.lower_ + " " + str(word.dep_) + "INV"})
                dependency_contexts_concat.append(word.lower_ + "_" + word.head.lower_ + "_" + str(word.dep_) + "INV")
    return dependency_contexts, dependency_contexts_concat
dependency_contexts = extract_dep_context(doc)[1]
dependency_contexts

['austrailian_scientists_amodINV',
 'scientists_austrailian_amod',
 'scientists_discovers_nsubjINV',
 'discovers_scientists_nsubj',
 'discovers_star_dobj',
 'star_with_prep',
 'star_discovers_dobjINV',
 'with_telescope_pobj',
 'with_star_prepINV',
 'telescope_with_pobjINV']

### Extract conll format

In [18]:
# https://github.com/explosion/spaCy/issues/533#issuecomment-254774296
def extract_conll_format(doc):
    result = []
    conll = []
    for sent in doc.sents:
        for i, word in enumerate(sent):
            if word.head is word:
                head_idx = 0
            else:
                 head_idx = word.head.i + 1
            conll.extend((i+1, word.lower_, word.lemma_, word.pos_, word.tag_, "_", head_idx, word.dep_, str(head_idx) + ":"+ word.dep_, "_"))
            result.append(" ".join(str(x) for x in conll))
            conll = []
    return result

conll_test = extract_conll_format(doc)
conll_test

['1 austrailian austrailian ADJ JJ _ 2 amod 2:amod _',
 '2 scientists scientist NOUN NNS _ 0 ROOT 0:ROOT _',
 '3 .... .... PUNCT . _ 2 punct 2:punct _',
 '1 discovers discover VERB VBZ _ 0 ROOT 0:ROOT _',
 '2 ten ten NUM CD _ 6 nummod 6:nummod _',
 '3 stars star NOUN NNS _ 4 dobj 4:dobj _',
 '4 with with ADP IN _ 6 prep 6:prep _',
 '5 telescope telescope NOUN NN _ 7 pobj 7:pobj _']

### Create conll format file

In [ ]:
with open("hatespeech_dep_conll", "w+") as conll_file:
    for index, row in df.iterrows():
        for entry in row["conllFormat"]:
            conll_file.write(entry+"\n")
        conll_file.write("\n")
conll_file.close()

### Load dependency embedding